module.exports = {
  apps: [
    {
      name: 'lms-api',
      script: '../../node_modules/ts-node/dist/bin.js',
      args: '--transpile-only src/main.ts',
      cwd: __dirname,
      interpreter: 'node',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '1G',
      env: {
        NODE_ENV: 'development',
        PORT: 3001,
        DATABASE_URL: 'postgresql://postgres:djib123@localhost:5432/lms?schema=public',
        REDIS_HOST: 'localhost',
        REDIS_PORT: 6379,
        MEILISEARCH_HOST: 'http://localhost:7700',
        MEILISEARCH_API_KEY: '',
        JWT_SECRET: 'lms-dev-jwt-secret-change-in-production',
        JWT_REFRESH_SECRET: 'lms-dev-refresh-secret-change-in-production',
        JWT_EXPIRES_IN: '15m',
        JWT_REFRESH_EXPIRES_IN: '7d',
        FRONTEND_URL: 'http://localhost:3000',
        ALLOWED_ORIGINS: 'http://localhost:3000,http://localhost:3001',
        ENCRYPTION_KEY: '0000000000000000000000000000000000000000000000000000000000000001',
        STRIPE_SECRET_KEY: 'sk_test_placeholder',
        STRIPE_WEBHOOK_SECRET: 'whsec_placeholder',
        STRIPE_PUBLISHABLE_KEY: 'pk_test_placeholder',
        MUX_TOKEN_ID: 'placeholder',
        MUX_TOKEN_SECRET: 'placeholder',
        MUX_WEBHOOK_SECRET: 'placeholder',
        AWS_ACCESS_KEY_ID: 'placeholder',
        AWS_SECRET_ACCESS_KEY: 'placeholder',
        AWS_REGION: 'us-east-1',
        AWS_BUCKET: 'lms-platform-dev',
        THROTTLE_TTL: '60',
        THROTTLE_LIMIT: '100',
      },
    },
  ],
};
