// Load secrets from .env — never hardcode credentials here
require('dotenv').config({ path: __dirname + '/.env' });

module.exports = {
  apps: [
    {
      name: 'lms-api',
      script: '../../node_modules/ts-node/dist/bin.js',
      args: '--transpile-only src/main.ts',
      cwd: __dirname,
      interpreter: 'node',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '1G',
      // All secrets come from .env (gitignored) — nothing sensitive here
      env: {
        NODE_ENV: process.env.NODE_ENV || 'development',
        PORT: process.env.PORT || 3001,
        DATABASE_URL: process.env.DATABASE_URL,
        REDIS_HOST: process.env.REDIS_HOST || 'localhost',
        REDIS_PORT: process.env.REDIS_PORT || 6379,
        MEILISEARCH_HOST: process.env.MEILISEARCH_HOST || 'http://localhost:7700',
        MEILISEARCH_API_KEY: process.env.MEILISEARCH_API_KEY || '',
        JWT_SECRET: process.env.JWT_SECRET,
        JWT_REFRESH_SECRET: process.env.JWT_REFRESH_SECRET,
        JWT_EXPIRES_IN: process.env.JWT_EXPIRES_IN || '15m',
        JWT_REFRESH_EXPIRES_IN: process.env.JWT_REFRESH_EXPIRES_IN || '7d',
        FRONTEND_URL: process.env.FRONTEND_URL || 'http://localhost:3000',
        ALLOWED_ORIGINS: process.env.ALLOWED_ORIGINS || 'http://localhost:3000',
        ENCRYPTION_KEY: process.env.ENCRYPTION_KEY,
        STRIPE_SECRET_KEY: process.env.STRIPE_SECRET_KEY,
        STRIPE_WEBHOOK_SECRET: process.env.STRIPE_WEBHOOK_SECRET,
        STRIPE_PUBLISHABLE_KEY: process.env.STRIPE_PUBLISHABLE_KEY,
        MUX_TOKEN_ID: process.env.MUX_TOKEN_ID,
        MUX_TOKEN_SECRET: process.env.MUX_TOKEN_SECRET,
        MUX_WEBHOOK_SECRET: process.env.MUX_WEBHOOK_SECRET,
        AWS_ACCESS_KEY_ID: process.env.AWS_ACCESS_KEY_ID,
        AWS_SECRET_ACCESS_KEY: process.env.AWS_SECRET_ACCESS_KEY,
        AWS_REGION: process.env.AWS_REGION || 'us-east-1',
        AWS_BUCKET: process.env.AWS_BUCKET,
        THROTTLE_TTL: process.env.THROTTLE_TTL || '60',
        THROTTLE_LIMIT: process.env.THROTTLE_LIMIT || '100',
        SMTP_HOST: process.env.SMTP_HOST,
        SMTP_PORT: process.env.SMTP_PORT,
        SMTP_USER: process.env.SMTP_USER,
        SMTP_PASS: process.env.SMTP_PASS,
        SMTP_FROM: process.env.SMTP_FROM,
      },
    },
  ],
};
